# Generated by Django 3.2.7 on 2021-10-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('ChartType', models.CharField(max_length=30)),
                ('CustomerId', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=30)),
                ('DaysOverdue', models.IntegerField()),
                ('AmountOutstanding', models.IntegerField()),
                ('Recovery', models.IntegerField()),
            ],
        ),
    ]
