# Generated by Django 3.2.7 on 2021-10-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='Date',
            field=models.CharField(max_length=10),
        ),
    ]
